[workspace]
members = [
    "cli",
    "lib/ikigai-lang",
    "lib/ikigai-providers",
    "lib/ikigai-stdlib"
]
resolver = "2"

[workspace.package]
version = "0.0.1"
description = "A small language for living data"
homepage = ""
repository = ""
documentation = ""
license = ""
categories = ["database"]
keywords = [""]
authors = ["Ángel Iglesias Préstamo <angel.iglesias.prestamo@gmail.com>"]
edition = "2024"
rust-version = "1.88.0"

[workspace.dependencies]
# external dependencies
polars = {version = "0.51.0", features = ["lazy"]}
thiserror = "2.0.17"
indexmap = "2.12.0"

# internal dependencies
ikigai-lang = { path = "./lib/ikigai-lang" }
ikigai-providers = { path = "./lib/ikigai-providers" }
ikigai-stdlib = { path = "./lib/ikigai-stdlib" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
