[package]
name = "ikigai-core"
version = "0.0.1"
description = "A library for working with ShExML"
homepage = ""
repository = ""
documentation = ""
license = ""
categories = ["database"]
keywords = ["shexml", "xml", "json", "rdf"]
authors = ["Ángel Iglesias Préstamo <angel.iglesias.prestamo@gmail.com>"]
edition = "2024"
rust-version = "1.88.0"

[dependencies]
logos = "0.15.1"
chumsky = { version= "0.11.1", features = ["pratt"]}
polars = {version = "0.51.0", features = ["lazy"]}
rand = "0.9.2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
